
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'C5B469704DC7408B291E016C1BAD23B6'
    
_lr_action_items = {'DIVIDE':([4,5,6,12,13,14,15,],[8,-8,-7,-6,-5,8,8,]),'NUMBER':([3,8,9,10,11,],[5,5,5,5,5,]),'TIMES':([4,5,6,12,13,14,15,],[9,-8,-7,-6,-5,9,9,]),'EQUALS':([1,],[3,]),'NAME':([0,],[1,]),'$end':([2,4,5,6,7,12,13,14,15,],[0,-4,-8,-7,-1,-6,-5,-2,-3,]),'MINUS':([4,5,6,7,12,13,14,15,],[-4,-8,-7,11,-6,-5,-2,-3,]),'PLUS':([4,5,6,7,12,13,14,15,],[-4,-8,-7,10,-6,-5,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assign':([0,],[2,]),'term':([3,10,11,],[4,14,15,]),'factor':([3,8,9,10,11,],[6,12,13,6,6,]),'expr':([3,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assign","S'",1,None,None,None),
  ('assign -> NAME EQUALS expr','assign',3,'p_assign','yacc.py',7),
  ('expr -> expr PLUS term','expr',3,'p_expr','yacc.py',11),
  ('expr -> expr MINUS term','expr',3,'p_expr','yacc.py',12),
  ('expr -> term','expr',1,'p_expr','yacc.py',13),
  ('term -> term TIMES factor','term',3,'p_term','yacc.py',18),
  ('term -> term DIVIDE factor','term',3,'p_term','yacc.py',19),
  ('term -> factor','term',1,'p_term','yacc.py',20),
  ('factor -> NUMBER','factor',1,'p_factor','yacc.py',25),
]
